# Generated by Django 3.2.7 on 2021-10-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartloop_exercise', '0003_auto_20211006_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(default='NEW', max_length=15),
        ),
    ]
